AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Builds serverless API, complete with Lambda functions,
  API Gateway, SQS Queues, DynamoDB table, and an S3 bucket.
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        TABLE_NAME: !Ref DemoTable
        SQS_QUEUE_URL: !Ref DemoQueue
Parameters:
  DataBucketName:
    Type: String
    Description: S3 bucket where CSV files are placed
    Default: gstafford-demo-data
  SubdomainName:
    Type: String
    Description: Domain or subdomain name referenced by the API
    Default: api.example-api.com
  CertificateArn:
    Type: String
    Description: Arn of domain's public wildcard TLS certificate
    Default: arn:aws:acm:us-east-1:931066906971:certificate/57fd98d2-a4ee-410a-9d5c-a755192f0fe6
  HostedZoneName:
    Type: String
    Description: Route53's Hosted Zone name
    Default: example-api.com. # don't miss the dot at the end
Resources:
  DemoServerlessApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
  ApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref SubdomainName
      CertificateArn: !Ref CertificateArn
    DependsOn: DemoServerlessApi
  GetMessagesFunction:
    Type: AWS::Serverless::Function
    Description: Get all messages in DynamoDB table (scan)
    Properties:
      Description: Get all messages in DynamoDB table (scan)
      CodeUri: lambda_apigtw_to_dynamodb/
      Handler: app.getMessages
      Runtime: nodejs10.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DemoTable
      Events:
        getMessages:
          Type: Api
          Properties:
            Path: /message
            Method: get
            RestApiId: !Ref DemoServerlessApi
  GetMessageFunction:
    Type: AWS::Serverless::Function
    Description: Get single message based on timestamp and location
    Properties:
      Description: Get single message based on timestamp and location
      CodeUri: lambda_apigtw_to_dynamodb/
      Handler: app.getMessage
      Runtime: nodejs10.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DemoTable
      Events:
        getMessages:
          Type: Api
          Properties:
            Path: /message/{date}
            Method: get
            RestApiId: !Ref DemoServerlessApi
  PostMessageFunction:
    Type: AWS::Serverless::Function
    Description: Create new message item in DynamoDB table
    Properties:
      Description: Create new message item in DynamoDB table
      CodeUri: lambda_apigtw_to_dynamodb/
      Handler: app.postMessage
      Runtime: nodejs10.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DemoTable
      Events:
        postMessage:
          Type: Api
          Properties:
            Path: /message
            Method: post
            RestApiId: !Ref DemoServerlessApi
  PutMessageFunction:
    Type: AWS::Serverless::Function
    Description: Update message item in DynamoDB table
    Properties:
      Description: Update message item in DynamoDB table
      CodeUri: lambda_apigtw_to_dynamodb/
      Handler: app.putMessage
      Runtime: nodejs10.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DemoTable
      Events:
        putMessage:
          Type: Api
          Properties:
            Path: /message/{date}
            Method: put
            RestApiId: !Ref DemoServerlessApi
  DeleteMessageFunction:
    Type: AWS::Serverless::Function
    Description: Delete message item in DynamoDB table
    Properties:
      Description: Delete message item in DynamoDB table
      CodeUri: lambda_apigtw_to_dynamodb/
      Handler: app.deleteMessage
      Runtime: nodejs10.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DemoTable
      Events:
        deleteMessage:
          Type: Api
          Properties:
            Path: /message/{date}
            Method: delete
            RestApiId: !Ref DemoServerlessApi
  SqsToDynamoDbFunction:
    Type: AWS::Serverless::Function
    Description: Responds to SQS Event - Sends to Dynamodb
    Properties:
      Description: Post new message to SQS
      CodeUri: lambda_sqs_to_dynamodb/
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DemoTable
      Events:
        SqsToDynamoDb:
          Type: SQS
          Properties:
            Queue: !GetAtt DemoQueue.Arn
            BatchSize: 10
            Enabled: true
  DemoDataBucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - S3ToSQSFunctionPermission
    Properties:
      BucketName: !Ref DataBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt S3ToSQSFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .csv
  S3ToSQSFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref S3ToSQSFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${DataBucketName}'
      SourceAccount: !Ref AWS::AccountId
  S3ToSQSFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: allowLogging
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
        - PolicyName: getObjects
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${DataBucketName}/*'
        - PolicyName: produceToQueue
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt DemoQueue.Arn
  S3ToSQSFunction:
    Type: AWS::Serverless::Function
    Description: Respond to S3 Events
    Properties:
      Description: Responds to S3 Event - Sends to SQS
      CodeUri: lambda_s3_to_sqs/
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Role: !GetAtt S3ToSQSFunctionExecutionRole.Arn
  DemoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: date
          AttributeType: S
        - AttributeName: time
          AttributeType: S
      KeySchema:
        - AttributeName: date
          KeyType: HASH
        - AttributeName: time
          KeyType: RANGE
  DemoQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - DeadLetterQueue
            - Arn
        maxReceiveCount: 5
  DeadLetterQueue:
    Type: AWS::SQS::Queue
  ApiDomain:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      RecordSets:
        - Name: !Ref SubdomainName
          Type: A
          AliasTarget:
            DNSName: !GetAtt ApiDomainName.DistributionDomainName
            HostedZoneId: Z2FDTNDATAQYW2 # static ID for CloudFront aliases
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: ApiDomain
    Properties:
      Name: TestApiKey
      Enabled: 'true'
      StageKeys:
        - RestApiId: !Ref DemoServerlessApi
          StageName: Prod
  ApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: ApiDomain
    Properties:
      DomainName: !Ref SubdomainName
      RestApiId: !Ref DemoServerlessApi
      Stage: !Sub '${DemoServerlessApiProdStage}' # logical id of API GW stage created by SAM
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: ApiDomain
    Properties:
      ApiStages:
        - ApiId: !Ref DemoServerlessApi
          Stage: !Sub '${DemoServerlessApiProdStage}'  # logical id of API GW stage created by SAM
      Quota:
        Limit: 5000
        Period: MONTH
      Throttle:
        BurstLimit: 200
        RateLimit: 100
      UsagePlanName: DemoUsagePlan
  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan
Outputs:
  MyStacksRegion:
    Description: 'Region where cfn stack is located'
    Value: !Ref AWS::Region
  DemoBucket:
    Description: 'S3 bucket where CSV files are placed'
    Value: !Ref DataBucketName
  DemoTable:
    Description: 'Name of DynamoDB table'
    Value: !Ref DemoTable
  DemoQueueArn:
    Description: 'Arn of SQS Queue'
    Value: !GetAtt DemoQueue.Arn
  DemoQueueUrl:
    Description: 'URL of SQS Queue'
    Value: !Ref DemoQueue
  GetMessagesApi:
    Description: 'Example API Gateway endpoint: GetMessagesFunction'
    Value: !Sub "https://${DemoServerlessApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getMessages/"