version: 0.2

env:
  variables:
      AWS_REGION: "us-east-1"
      TABLE_NAME: "iot-dynamodb-IotDemoTable-1096ZA2SMLFQC"
      SQS_QUEUE_ARN: "arn:aws:sqs:us-east-1:931066906971:iot-dynamodb-IotDemoQueue-1WY8QV5BPVQF9"

phases:
  install:
    commands:
      - pip install pytest
    runtime-versions:
      python: 3.7
  build:
    commands:
      - sh buildspec_files/test_sqs_to_dynamo.sh